### ISSUE TITLE
is having Spotify or pyrogram neccassary?

### ISSUE THREAD

**Issue by MasoudRahmani** [An0nimia/DeezSpot_bot#52]
Spotify is blocked in my region and I only need deezer, is it necessary to input my Spotify credential since it would return 403 or 404 page.

Also I have a bot which i created using [BotFather ](https://t.me/BotFather)why should I get a application id from telegram when Bot Token would suffice?

**Comment by An0nimia** [comment]
Try and you will know by yourself.
