### ISSUE TITLE
python3.9 configparser raise KeyError(key)!!

### ISSUE THREAD

**Issue by MasoudRahmani** [An0nimia/DeezSpot_bot#53]
After i try to run the app, when it tries to check config file using `check_config_file(config)` function, program encounters an exception.

I checked the code below, if my config is wrong it should print something but it's throwing an exception.
```
if not "arl" in config['deez_login']:
		print("Something went wrong with the login token in the configuration file")
		exit()

```
My Exception:
```
hesam@zeus:~$ python3.9 /home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/deez_bot.py
1): TEST MODE
2): COOL MODE
3): TEST MODE (NO ZIP)
4): COOL MODE (NO ZIP)
How to use it?: 3
Traceback (most recent call last):
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/deez_bot.py", line 8, in <module>
    from configs.set_configs import SetConfigs
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/configs/set_configs.py", line 14, in <module>
    check_config_file(config)
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/utils/utils.py", line 44, in check_config_file
    if not "arl" in config['deez_login']:
  File "/usr/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'deez_login'

```

System:
Python 3.9.5
Operating system | Ubuntu Linux 20.04.3

**Comment by An0nimia** [comment]
@MasoudRahmani there is deez_login in your configuration file?

**Comment by MasoudRahmani** [comment]
yes.
```
[deez_login]
mail = mr**@gmail.com
pwd = nP***L9
arl = bc4a8dfb6b1**359b6362ff4bd17544
```

**Comment by An0nimia** [comment]
@MasoudRahmani have you updated to the latest bot version?

**Comment by An0nimia** [comment]
@MasoudRahmani are you sure that you set the right config file?

**Comment by An0nimia** [comment]
@An0nimia In configs/bot_settings.py should be a variable named "settings_file" is that file right?

**Comment by MasoudRahmani** [comment]
![image](https://user-images.githubusercontent.com/5321268/151148870-25bba8c2-56f9-462d-8c19-aaedc9987e18.png)

**Comment by An0nimia** [comment]
@MasoudRahmani may you do the same for .deez_settings.ini kindly?

**Comment by MasoudRahmani** [comment]
ofc, Thank you for your time.
![image](https://user-images.githubusercontent.com/5321268/151149514-bb6fcdc9-9368-4a07-8a0d-f3173553d520.png)

**Comment by MasoudRahmani** [comment]
i tried to input them directly, without using config file and it works. i don't know why it has problem.
But since Spotify is banned, i can't continue. i wish services used was optional. Thanks

**Comment by An0nimia** [comment]
@MasoudRahmani you should execute it from the same directory

**Comment by An0nimia** [comment]
@MasoudRahmani for this it doesn't find nothing cause the settings is in a different folder from the execute folder

**Comment by An0nimia** [comment]
@MasoudRahmani try vpn, create spotify credentials in another part of the world

**Comment by MasoudRahmani** [comment]
> @MasoudRahmani for this it doesn't find nothing cause the settings is in a different folder from the execute folder

OOkay, so using absolute path, resolved the error. thanks
