### ISSUE TITLE
Low quality (.ogg audio)

### ISSUE THREAD

**Issue by KelvinCrag** [An0nimia/DeezSpot_bot#55]
It has come to notice that deez bot no longer provide .mp3 format with 320kb/s audio quality but it now comes in .ogg with ~160kb/s :(

**Comment by An0nimia** [comment]
@KelvinCrag buy spoty premium

**Comment by KelvinCrag** [comment]
Sigh. You don't need to be rude, of course, I'm grateful for your work. I only brought something to your notice mate.

PS: So I switched to FLAC/Very high option in bot.. seems that's the new 320kb/s

**Comment by An0nimia** [comment]
@KelvinCrag sorry? I wasn't rude I was cold
